name: other workflow

on:
  pull_request:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "; echo 'attacker controlled code'; #" > artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.txt
