name: other workflow

on:
  pull_request:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "shyam baba" >> artifact.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./artifact.txt
